module.exports.consoles = [
  {
    key: 'PS4',
    name: 'PlayStation 4',
    description: null,
    emote: '🔵',
    lockAvailable: false,
    default: false,
  },
  {
    key: 'PS5',
    name: 'PlayStation 5',
    description: null,
    emote: '⚪',
    lockAvailable: true,
    default: false,
  },
  {
    key: 'NS',
    name: 'Nintendo Switch',
    description: null,
    emote: '🔴',
    lockAvailable: false,
    default: false,
  },
  {
    key: 'NS2',
    name: 'Nintendo Switch 2',
    description: null,
    emote: '🟠',
    lockAvailable: false,
    default: false,
  },
  {
    key: 'XBO',
    name: 'Xbox One',
    description: null,
    emote: '🟢',
    lockAvailable: false,
    default: false,
  },
  {
    key: 'XBX',
    name: 'Xbox Series X',
    description: null,
    emote: '⚫',
    lockAvailable: false,
    default: false,
  },
  {
    key: 'STM',
    name: 'PC (Steam)',
    description: null,
    emote: '🟣',
    lockAvailable: false,
    default: true,
  },
  {
    key: 'EPC',
    name: 'PC (Epic Games)',
    description: null,
    emote: '🟡',
    lockAvailable: false,
    default: false,
  },
];
