const {
  RACE_ITEMS_FFA,
  RACE_ITEMS_DUOS,
  RACE_ITEMS_3v3v3v3,
  RACE_ITEMS_4v4v4,
  RACE_ITEMS_6v6,
  RACE_ITEMLESS_1v1,
  RACE_ITEMLESS_FFA,
  RACE_ITEMLESS_DUOS,
  RACE_ITEMLESS_3v3v3v3,
  RACE_ITEMLESS_4v4v4,
  RACE_ITEMLESS_6v6,
  INSTA_DUOS,
  INSTA_3v3v3v3,
  INSTA_4v4v4,
  INSTA_6v6,
} = require('./models/lobby');

module.exports.lobbyTypes = [
  {
    key: RACE_ITEMS_FFA,
    name: 'FFA',
    description: null,
    emote: null,
    default: true,
  },
  {
    key: RACE_ITEMS_DUOS,
    name: 'Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMS_3v3v3v3,
    name: 'Quads (3v3v3v3)',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMS_4v4v4,
    name: 'Triples (4v4v4)',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMS_6v6,
    name: '6v6',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_1V1,
    name: 'Itemless 1 vs. 1',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_FFA,
    name: 'Itemless FFA',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_DUOS,
    name: 'Itemless Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_3v3v3v3,
    name: 'Itemless Quads (3v3v3v3)',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_4v4v4,
    name: 'Itemless Triples (4v4v4)',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: RACE_ITEMLESS_6v6,
    name: 'Itemless 6v6',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_DUOS,
    name: 'Insta Duos',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_3v3v3v3,
    name: 'Insta Quads (3v3v3v3)',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_4v4v4,
    name: 'Insta Triples (4v4v4)',
    description: null,
    emote: null,
    default: false,
  },
  {
    key: INSTA_6v6,
    name: 'Insta 6v6',
    description: null,
    emote: null,
    default: false,
  },
];
